name: CI/CD y Cypress E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: 游닌 Descargar el c칩digo
        uses: actions/checkout@v4

      - name: 游댢 Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: "20" 
          cache: "yarn" 

      - name: 游닍 Instalar dependencias con Yarn
        run: yarn install --frozen-lockfile

      - name: 游빍 Correr tests con coverage
        run: yarn test --coverage

      - name: 游늵 Subir los resultados a Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-actions

      - name: 游늶 Subir los detalles de los test a Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1

  cypress-run:
    runs-on: ubuntu-latest
    needs: ci
    strategy:
      fail-fast: false
      matrix:
        containers: ["cnt-1", "cnt-2"]
    steps:
      - name: 游닌 Descargar el c칩digo
        uses: actions/checkout@v4

      - name: 游댢 Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: 游닍 Instalar dependencias con Yarn
        run: yarn install --frozen-lockfile

      - name: 游빍 Ejecutar Cypress en paralelo
        uses: cypress-io/github-action@v6
        with:
          start: yarn dev
          wait-on: "http://localhost:5173"
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: cypress-run
    steps:
      - name: 游닌 Descargar el c칩digo
        uses: actions/checkout@v4

      - name: 游 Deploy en Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
